package it.polimi.ingsw.View.GUI.ViewControllers;

import it.polimi.ingsw.Exceptions.MalformedMessageException;
import it.polimi.ingsw.Messages.MessageFactory;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;

import java.util.*;

/**
 * controller of the selection of the end of the game
 */
public class EndGameController extends ViewController {

    @FXML
    private AnchorPane anchorPane;

    @FXML
    private Label labelPlayer1;

    @FXML
    private Label labelPoints1;

    @FXML
    private Label labelPlayer2;

    @FXML
    private Label labelPoints2;

    @FXML
    private Label labelPlayer3;

    @FXML
    private Label labelPoints3;

    @FXML
    private Label labelPlayer4;

    @FXML
    private Label labelPoints4;

    @FXML
    private Button exitButton;

    @FXML
    private Label winner;


    private List<Label> players;

    private List<Label> points;


    @FXML
    public void initialize() {
        players = new LinkedList<>();
        points = new LinkedList<>();

        players.add(labelPlayer1);
        points.add(labelPoints1);
        players.add(labelPlayer2);
        points.add(labelPoints2);
        players.add(labelPlayer3);
        points.add(labelPoints3);
        players.add(labelPlayer4);
        points.add(labelPoints4);

        for (Label label : players)
            label.setVisible(false);
        for (Label label : points)
            label.setVisible(false);

        exitButton.addEventHandler(MouseEvent.MOUSE_RELEASED, this::onExitButtonClicked);
    }


    /**
     * manages the end of the game
     * @param map contains the nicknames of the players and the score associated
     */
    public void showEndGame(Map<String, Integer> map, String winner) {

        LinkedHashMap<String, Integer> sortedMap = new LinkedHashMap<>();
        map.entrySet()
                .stream()
                .sorted(Map.Entry.comparingByValue(Comparator.reverseOrder()))
                .forEachOrdered(x -> sortedMap.put(x.getKey(), x.getValue()));

        int i = 0;

        for (String player : sortedMap.keySet()) {
            players.get(i).setText(player);
            players.get(i).setVisible(true);
            points.get(i).setText(map.get(player).toString());
            points.get(i).setVisible(true);
            i++;
        }
        String text = winner + "  is the winner!";
        this.winner.setText(text);
        this.winner.setVisible(true);
    }

    /**
     * allows the player to exit the game
     * @param event represents the event generated by the button when clicked
     */
    private void onExitButtonClicked(Event event){
        try {
            String message = MessageFactory.buildDisconnection("Disconnection request.", getModelReference().getPersonalNickname());
            getGUIReference().notifyInteraction(message);
        } catch (MalformedMessageException e){
            e.printStackTrace();
        }
    }

}
