package it.polimi.ingsw.View.GUI.ViewControllers;

import javafx.application.Platform;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;


public class LoadingController extends ViewController{

    @FXML
    private Pane pane;
    @FXML
    private Button exitButton;

    /**
     * initializes the login scene
     */
    @FXML
    public void initialize(){

        exitButton.addEventHandler(MouseEvent.MOUSE_CLICKED, this::onExitButtonClicked);

    }

    /**
     * disconnects the player from the game closing the scene
     * @param event represents the event generated by the button when clicked
     */
    private void onExitButtonClicked(Event event) {
        Platform.exit();
        System.exit(0);
    }

    /**
     * closes the scene
     */
    public void closeScene(){
        pane.getScene().getWindow().hide();
    }

}
