package it.polimi.ingsw.View.GUI.ViewControllers;

import it.polimi.ingsw.Exceptions.MalformedMessageException;
import it.polimi.ingsw.Messages.MessageFactory;
import it.polimi.ingsw.View.GUI.GUIHandler;
import javafx.event.Event;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.control.TextField;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;

/**
 * represents the controller associated to the login scene
 */
public class LoginController extends ViewController{

    @FXML
    private Pane pane;
    @FXML
    private Label invalidNicknameLabel;
    @FXML
    private TextField nicknameField;
    @FXML
    private MenuItem soloButton;
    @FXML
    private MenuItem singlePlayerButton;
    @FXML
    private MenuItem twoPlayersButton;
    @FXML
    private MenuItem threePlayersButton;
    @FXML
    private MenuItem fourPlayersButton;
    @FXML
    private Button joinButton;
    @FXML
    private Button reconnectButton;

    /**
     * Initializes the login scene
     */
    @FXML
    public void initialize() {

        invalidNicknameLabel.setVisible(false);

        soloButton.setOnAction(this::onSoloButtonClicked);
        singlePlayerButton.setOnAction(this::onSinglePlayerButtonClicked);
        twoPlayersButton.setOnAction(this::onTwoPlayersButtonClicked);
        threePlayersButton.setOnAction(this::onThreePlayersButtonClicked);
        fourPlayersButton.setOnAction(this::onFourPlayersButtonClicked);

        joinButton.addEventHandler(MouseEvent.MOUSE_CLICKED, this::onJoinButtonClicked);

        reconnectButton.addEventHandler(MouseEvent.MOUSE_CLICKED, this::onReconnectButtonClicked);

    }

    /**
     * handles the creation of a new local game
     * @param event represents the event generated by the button when clicked
     */
    private void onSoloButtonClicked(Event event){
        if(checkUsername()){
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), true, 1);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifySoloInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            } catch (MalformedMessageException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the creation of a new single player game
     * @param event represents the event generated by the button when clicked
     */
    private void onSinglePlayerButtonClicked(Event event){
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), true, 1);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            } catch (MalformedMessageException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the creation of a new 2-players game
     * @param event represents the event generated by the button when clicked
     */
    private void onTwoPlayersButtonClicked(Event event){
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), true, 2);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            }catch (MalformedMessageException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the creation of a new 3-players game
     * @param event represents the event generated by the button when clicked
     */
    private void onThreePlayersButtonClicked(Event event){
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), true, 3);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            }catch (MalformedMessageException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the creation of a new 4-players game
     * @param event represents the event generated by the button when clicked
     */
    private void onFourPlayersButtonClicked(Event event){
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), true, 4);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            }catch (MalformedMessageException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the join to an existing game
     * @param event represents the event generated by the button when clicked
     */
    private void onJoinButtonClicked(Event event) {
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildConnection("Connection request.", nicknameField.getText(), false, 0);
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            }catch (MalformedMessageException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * handles the reconnection to an existing game
     * @param event represents the event generated by the button when clicked
     */
    private void onReconnectButtonClicked(Event event){
        if(checkUsername()) {
            try {
                String message = MessageFactory.buildReconnection("Reconnection request.", nicknameField.getText());
                getGUIReference().notifyNickname(nicknameField.getText());
                getGUIReference().notifyInteraction(message);
                LoadingController controller = new LoadingController();
                GUIHandler.loadRoot(controller, "/FXML/loading.fxml");
            }catch (MalformedMessageException e){
                e.printStackTrace();
            }
        }
    }

    /**
     *
     * @return true if the nickname field is not empty, false otherwise
     */
    private boolean checkUsername(){
        if(!nicknameField.getText().isEmpty()){
            return true;
        }else{
            invalidNicknameLabel.setVisible(true);
            return false;
        }
    }

}
